---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: no-commit-to-branch  # prevent direct commits to main branch
    - id: check-toml
    - id: end-of-file-fixer
      name: Make sure that there is an empty line at the end
    - id: trailing-whitespace
      name: Remove trailing whitespace at end of line
    - id: check-added-large-files
    - id: check-merge-conflict
      name: Check that merge conflicts are not being committed
    - id: debug-statements
      name: Detect accidentally committed debug statements
    - id: detect-private-key
      name: Detect if private key is added to the repository
    - id: mixed-line-ending
    - id: check-docstring-first
      name: Detect if mixed line ending is used (\r vs. \r\n)
      exclude: ^.*/.*_vendor/
    - id: fix-encoding-pragma
      name: Remove encoding header from Python files
      exclude: ^.*/.*_vendor/
      args:
        - --remove


  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
        args: [--py312-plus, --add-import, 'from __future__ import annotations']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.4
    hooks:
      - id: ruff
      - id: ruff-format
