---
services:
  place-orders:
    tty: true
    env_file:
      - place-orders/.env
    build:
      context: ./place-orders
      dockerfile: Dockerfile
    container_name: place-orders
    networks:
      - demo
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
  bot-operator:
    tty: true
    build:
      context: ./bot-operator
      dockerfile: Dockerfile
    container_name: bot-operator
    networks:
      - demo
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy

  price-watch:
    tty: true
    build:
      context: ./price-watch
      dockerfile: Dockerfile
    container_name: price-watch
    networks:
      - demo
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:3.12.2-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - demo
    container_name: rabbitmq
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 10s
      retries: 5
    expose:
      - "5672"

networks:
  demo:
    name: "demo"
    driver: bridge
